"""
Task Selector Module
====================
Manages task selection and status tracking for the Ralph Wiggum Loop.

This is the simplified orchestrator that delegates:
- Parsing to strict JSON loading
- Validation to spec_validator module
- State management via TASKS.json (authoritative)
"""

import json
import os
import re
from typing import Optional
from datetime import datetime

from .spec_validator import validate_spec
from .config import LoopConfig

class TaskSelector:
    """Manages task selection and status tracking using TASKS.json as source of truth."""
    
    def __init__(self, config: Optional[LoopConfig] = None):
        """
        Initialize task selector.
        
        Args:
            config: Loop configuration object. If None, loads from env.
        """
        self.config = config or LoopConfig.from_env()
        self._tasks: list[dict] = []
        self._load_tasks()
    
    def _load_tasks(self) -> None:
        """Load tasks strictly from TASKS.json."""
        if os.path.exists(self.config.tasks_json_path):
            try:
                with open(self.config.tasks_json_path, 'r') as f:
                    self._tasks = json.load(f)
            except json.JSONDecodeError as e:
                print(f"[TASK] ⚠️ Failed to parse {self.config.tasks_json_path}: {e}")
                self._tasks = []
        else:
            print(f"[TASK] ⚠️ No task file found at {self.config.tasks_json_path}")
            self._tasks = []

    def _save_tasks(self) -> bool:
        """Save current task state to TASKS.json and sync to markdown."""
        try:
            # Save JSON (Source of Truth)
            os.makedirs(os.path.dirname(self.config.tasks_json_path), exist_ok=True)
            with open(self.config.tasks_json_path, 'w') as f:
                json.dump(self._tasks, f, indent=2)
            
            # Sync to Markdown (View)
            self._sync_to_markdown()
            return True
        except Exception as e:
            print(f"[TASK] ❌ Failed to save tasks: {e}")
            return False

    def _sync_to_markdown(self) -> None:
        """Generate/Update task.md based on current JSON state."""
        try:
            lines = [
                "# Task List",
                "",
                f"> Generated: {datetime.now().isoformat()}",
                "> Source: TASKS.json (Do not edit this file manually)",
                "",
            ]
            
            # Group by phase/category (using first tag)
            current_category = None
            for task in self._tasks:
                tags = task.get("tags", [])
                category = tags[0] if tags else "general"
                
                if category != current_category:
                    lines.append(f"\n## {category.title()}")
                    current_category = category
                
                # Checkbox state
                status = task.get("status", "pending")
                check = " "
                if status == "complete":
                    check = "x"
                elif status == "failed":
                    check = "!"
                elif status == "in_progress":
                    check = "/"
                
                # Line construction
                line = f"- [{check}] {task.get('action', 'Unknown')} <!-- id: {task.get('id')} -->"
                
                # Append Outcome/Reason if present
                if status == "failed" and task.get("failure_reason"):
                    line += f" <!-- reason: {task['failure_reason']} -->"
                    
                lines.append(line)
            
            os.makedirs(os.path.dirname(self.config.task_md_path), exist_ok=True)
            with open(self.config.task_md_path, 'w') as f:
                f.write("\n".join(lines))
                
        except Exception as e:
            print(f"[TASK] ⚠️ Failed to sync markdown: {e}")

    def get_next(self) -> Optional[dict]:
        """
        Get the first incomplete task, respecting dependencies.
        
        Returns:
            Task dict if found, None if all complete/blocked
        """
        # Reload to ensure fresh state
        self._load_tasks()
        
        # Build Map for O(1) lookups
        task_map = {t['id']: t for t in self._tasks}
        
        for task in self._tasks:
            status = task.get("status", "pending")
            
            # Skip if done
            if status in ["complete", "failed"]:
                continue
            
            # Check dependencies
            dependencies = task.get("depends_on", [])
            deps_met = True
            
            for dep_id in dependencies:
                dep = task_map.get(dep_id)
                if not dep:
                    # Missing dependency is a blocker
                    print(f"[TASK] ⚠️ Task {task['id']} depends on missing task {dep_id}")
                    deps_met = False
                    break
                    
                dep_status = dep.get("status", "pending")
                
                if dep_status == "failed":
                    # Cascade failure
                    print(f"[TASK] ⛔ Task {task['id']} blocked by failed dependency {dep_id}")
                    self.mark_failed(task['id'], f"Dependency {dep_id} failed")
                    deps_met = False
                    break
                
                if dep_status != "complete":
                    deps_met = False
                    break
            
            if deps_met:
                return task
                
        return None
    
    def mark_complete(self, task_id: str) -> bool:
        """
        Mark a task as complete in TASKS.json.
        
        Args:
            task_id: Task identifier
            
        Returns:
            True if successfully marked
        """
        for task in self._tasks:
            if task['id'] == task_id:
                task['status'] = 'complete'
                task['completed_at'] = datetime.now().isoformat()
                
                if self._save_tasks():
                    print(f"[TASK] ✅ Marked task {task_id} complete")
                    return True
                return False
                
        print(f"[TASK] ❌ Task {task_id} not found")
        return False

    def mark_failed(self, task_id: str, reason: str = "") -> bool:
        """
        Mark a task as failed in TASKS.json.
        
        Args:
            task_id: Task identifier
            reason: Reason for failure
            
        Returns:
            True if successfully marked
        """
        for task in self._tasks:
            if task['id'] == task_id:
                task['status'] = 'failed'
                task['failure_reason'] = reason
                task['failed_at'] = datetime.now().isoformat()
                
                if self._save_tasks():
                    print(f"[TASK] ❌ Marked task {task_id} failed: {reason}")
                    return True
                return False
                
        return False
    
    def unmark(self, task_id: str) -> bool:
        """
        Reset a task to pending (used for retries).
        
        Args:
            task_id: Task identifier
        """
        for task in self._tasks:
            if task['id'] == task_id:
                task['status'] = 'pending'
                # Remove failure metadata if present
                task.pop('failure_reason', None)
                task.pop('failed_at', None)
                task.pop('completed_at', None)
                
                if self._save_tasks():
                    print(f"[TASK] 🔄 Reset task {task_id} to pending")
                    return True
        return False

    def validate_spec(self, task: dict, context_data: Optional[dict]) -> tuple[bool, list[str]]:
        """Validation delegate."""
        return validate_spec(task, context_data)
